api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle

urlpatterns = [
    path('v1/productos/', ProductoList.as_view(), name='producto_list'),
    path('v1/productos/<str:codigo>/', ProductoDetalle.as_view(), name='producto_detalle'),
]

fac/urls.py
from django.urls import path, include

from .reportes import imprimir_factura_recibo, imprimir_factura_list
from .views import ClienteView, ClienteNew, ClienteEdit, borrar_detalle_factura, clienteInactivar, FacturaView, facturas, ProductoView, borrar_detalle_factura

urlpatterns = [
    path("clientes/", ClienteView.as_view(), name="cliente_list"),
    path("clientes/new", ClienteNew.as_view(), name="cliente_new"),
    path("clientes/edit/<int:pk>", ClienteEdit.as_view(), name="cliente_edit"),
    path("clientes/estado/<int:id>", clienteInactivar, name="cliente_inactivar"),

    path("facturas/", FacturaView.as_view(), name="factura_list"),
    path("facturas/new", facturas, name="factura_new"),
    path('facturas/edit/<int:id>', facturas, name="factura_edit"),
    path("facturas/buscar-producto", ProductoView.as_view(), name="factura_producto"),

    path("facturas/borrar-detalle/<int:id>", borrar_detalle_factura, name="factura_borrar_detalle"),

    path("facturas/imprimir/<int:id>", imprimir_factura_recibo, name="factura_imprimir_one"),

    path("facturas/imprimir-todas/<str:f1>/<str:f2>", imprimir_factura_list, name="factura_imprimir_all"),
]

inv/urls.py
from django.urls import path

from inv.models import SubCategoria, UnidadMedida

from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, MarcaView, \
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
        MarcaView, MarcaNew, MarcaEdit, marca_inactivar, \
            UMView, UMNew, UMEdit, um_inactivar, \
                ProductoView, ProductoNew, ProductoEdit, producto_inactivar
            

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('marcas/', MarcaView.as_view(), name='marca_list'),
    path('marcas/new', MarcaNew.as_view(), name='marca_new'),
    path('marcas/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    path('marcas/inactivar/<int:id>', marca_inactivar, name='marca_inactivar'),

    path('um/', UMView.as_view(), name='um_list'),
    path('um/new', UMNew.as_view(), name='um_new'),
    path('um/edit/<int:pk>', UMEdit.as_view(), name='um_edit'),
    path('um/inactivar/<int:id>', um_inactivar, name='um_inactivar'),

    path('producto/', ProductoView.as_view(), name='producto_list'),
    path('producto/new', ProductoNew.as_view(), name='producto_new'),
    path('producto/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('producto/inactivar/<int:id>', producto_inactivar, name='producto_inactivar'),    
]

syscofa/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),    
]

fac/models.py
from tabnanny import verbose
from django.db import models

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

from bases.models import ClaseModelo, ClaseModelo2
from inv.models import Producto

# Create your models here.
class Cliente(ClaseModelo):
    """ modelo que representa un cliente """
    #example of choices
    NAT = 'Natural'
    JUR = 'Jurídica'
    TIPO_CLIENTE = [
        (NAT, 'Natural'),
        (JUR, 'Jurídica')
    ]

    nombres = models.CharField(
        max_length=100
    )

    apellidos = models.CharField(
        max_length=100
    )
    celular = models.CharField(
        max_length=20,
        null=True,
        blank=True
    )

    tipo = models.CharField(
        max_length=10,
        choices=TIPO_CLIENTE,
        default=NAT
    )

    def __str__(self):
        return '{} {}'.format(self.apellidos, self.nombres)

    def save(self):
        self.nombres = self.nombres.upper()
        self.apellidos = self.apellidos.upper()
        super(Cliente, self).save()

    class Meta:
        verbose_name_plural = 'Clientes'

class FacturaEnc(ClaseModelo2):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    def __str__(self):
        return '{}'.format('id')

    def save(self):
        self.total = self.sub_total - self.descuento
        super(FacturaEnc, self).save()

    class Meta:
        verbose_name_plural = "Encabezado Facturas"
        verbose_name = "Encabezado Factura"
        permissions = [
            ('sup_caja_facturaenc', 'Permiso de Supervisor de Caja Encabezado')
        ]

class FacturaDet(ClaseModelo2):
    factura = models.ForeignKey(FacturaEnc, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=0)
    precio = models.FloatField(default=0)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
        self.total = self.sub_total - float(self.descuento)
        super(FacturaDet, self).save()

    class Meta:
        verbose_name_plural = "Detalles Facturas"
        verbose_name = "Detalle Factura"
        permissions = [
            ('sup_caja_facturadet', 'Permiso de Supervisor de Caja Detalle')
        ]

# vigilamos el modelo facturadet con signals
@receiver(post_save, sender=FacturaDet)
def detalle_fac_guardar(sender, instance, **kwargs):
    factura_id = instance.factura.id   #id de factura
    producto_id = instance.producto.id #id de producto

    # modelo encabezado
    enc = FacturaEnc.objects.get(pk=factura_id)
    if enc:
        sub_total = FacturaDet.objects.filter(factura=factura_id) \
            .aggregate(sub_total=Sum('sub_total')).get('sub_total', 0.00)

        descuento = FacturaDet.objects.filter(factura=factura_id) \
            .aggregate(descuento=Sum('descuento')).get('descuento', 0.00)

        enc.sub_total = sub_total
        enc.descuento = descuento
        enc.save()

    # modelo producto
    prod = Producto.objects.filter(pk=producto_id).first()
    if prod: # si existe un producto
        cantidad = int(prod.existencia) - int(instance.cantidad)
        prod.existencia = cantidad
        prod.save()
    

fac/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):
    """Form definition for Cliente."""

    class Meta:
        """Meta definition for Clienteform."""
        model = Cliente
        fields = ['nombres', 'apellidos', 'tipo', 'celular', 'estado']
        exclude = ['um', 'fm', 'uc', 'fc']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #iteramos todos los campos del form
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    

fac/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from datetime import datetime
from django.contrib import messages

from django.contrib.auth import authenticate
from requests import post

from bases.views import Sin_Privilegios, VistaBaseCreate, VistaBaseEdit
from .models import Cliente, FacturaDet, FacturaEnc
from .models import Producto
from .forms import ClienteForm
from inv import views as inv

# Create your views here.
class ClienteView(Sin_Privilegios, generic.ListView):
    model = Cliente
    template_name = "fac/cliente_list.html"
    context_object_name = "obj"
    permission_required = "fac/view_cliente"

class ClienteNew(VistaBaseCreate):
    model = Cliente
    template_name = "fac/cliente_form.html"
    form_class = ClienteForm
    success_url = reverse_lazy('fac:cliente_list')
    permission_required = 'fac.add_cliente'

    def get(self, request, *args, **kwargs):
        print("sobre escribir get")
        
        try:
            t = request.GET["t"]
        except:
            t = None

        print(t)
        
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 't':t})

class ClienteEdit(VistaBaseEdit):
    model = Cliente
    template_name = "fac/cliente_form.html"
    form_class = ClienteForm
    success_url = reverse_lazy("fac:cliente_list") 
    permission_required = 'fac.change_cliente'

    def get(self, request, *args, **kwargs):
        print("sobre escribir get en editar")

        print(request)
        
        try:
            t = request.GET["t"]
        except:
            t = None

        print(t)
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form,t=t)
        print(form_class,form,context)
        return self.render_to_response(context)

@login_required(login_url='/login/') #necesitamos estar logeados
@permission_required("fac:change_cliente", login_url='/login/') #permiso requerido
def clienteInactivar(request, id):
    cliente = Cliente.objects.filter(pk=id).first()

    if request.method == "POST":
        if cliente: # si se creo el cliente
            #si cliente esta en true se cambia a false o viceversa
            cliente.estado = not cliente.estado 
            cliente.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")

    return HttpResponse("FAIL")
    
class FacturaView(Sin_Privilegios, generic.ListView):
    model = FacturaEnc
    template_name = "fac/factura_list.html"
    context_object_name = "obj"
    permission_required = 'fac.view_facturaenc'

@login_required(login_url='/login/') #necesitamos estar logeados
@permission_required("fac.change_facturaenc", login_url='bases:sin_privilegios') #permiso requerido
def facturas(request, id=None):
    template_name = "fac/facturas.html"
    encabezado = {
        'fecha': datetime.today()
    }
    detalle = {}
    clientes = Cliente.objects.filter(estado=True)

    if request.method == "GET":
        enc = FacturaEnc.objects.filter(pk=id).first()
        if not enc:
            encabezado = {
                'id': 0,
                'fecha': datetime.today,
                'cliente': 0,
                'sub_total': 0.00,
                'descuento': 0.00,
                'total': 0.00
            }
            detalle = None
        else:
            encabezado = {
                'id': enc.id,
                'fecha': enc.fecha,
                'cliente': enc.cliente,
                'sub_total': enc.sub_total,
                'descuento': enc.descuento,
                'total': enc.total
            }
            detalle = FacturaDet.objects.filter(factura=enc)
        
        contexto = {"enc":encabezado, "det":detalle, "clientes":clientes}
    
    if request.method == "POST":
        cliente = request.POST.get("enc_cliente")
        fecha = request.POST.get("fecha")
        cli = Cliente.objects.get(pk=cliente)

        if not id: #si no hay id, la factura es nueva
            enc = FacturaEnc(
                cliente = cli,
                fecha = fecha
            )
            if enc:
                enc.save()
                id = enc.id
        
        else:
            enc = FacturaEnc.objects.filter(pk=id).first()
            if enc: #ya existe el encabezado
                enc.cliente = cli
                enc.save()

        if not id:
            messages.error(request,'No Puedo Continuar No Pude Detectar No. de Factura')
            return redirect("fac:factura_list")

        codigo = request.POST.get("codigo")
        cantidad = request.POST.get("cantidad")
        precio = request.POST.get("precio")
        s_total = request.POST.get("sub_total_detalle")
        descuento = request.POST.get("descuento_detalle")
        total = request.POST.get("total_detalle")

        prod = Producto.objects.get(codigo=codigo)
        det = FacturaDet(
            factura = enc,
            producto = prod,
            cantidad = cantidad,
            precio = precio,
            sub_total = s_total,
            descuento = descuento,
            total = total
        )

        if det:
            det.save()

        return redirect("fac:factura_edit",id=id)
    
    return render(request, template_name, contexto)

class ProductoView(inv.ProductoView):
    template_name = "fac/buscar_producto.html"

def borrar_detalle_factura(request, id):
    template_name = "fac/factura_borrar_detalle.html"

    det = FacturaDet.objects.get(pk=id)

    if request.method == "GET":
        context = {"det": det}

    if request.method == "POST":
        usr = request.POST.get("usuario")
        pas = request.POST.get("pass")

        user = authenticate(username=usr, password=pas) # autenticamos al usuario

        if not user: # validamos si el usuario o la clave estan mal
            return HttpResponse("Usuario o clave incorrecta")

        if not user.is_active: # si el usuario no esta activo
            return HttpResponse("Usuario Inactivo")

        if user.is_superuser or user.has_perm("fac.sup_caja_facturadet"): # si es superusuario y tiene este permiso
            det.id = None
            det.cantidad = (-1 * det.cantidad)
            det.sub_total = (-1 * det.sub_total)
            det.decuento = (-1 * det.descuento)
            det.total = (-1 * det.total)
            det.save()

            return HttpResponse("ok")
        
        return HttpResponse("Usuario no autorizado")

    return render(request, template_name, context)


# class ClienteNew(SuccessMessageMixin, Sin_Privilegios, generic.CreateView):
#     model = Cliente
#     template_name = "fac/cliente_form.html"
#     context_object_name = "obj"
#     form_class = ClienteForm
#     success_url = reverse_lazy('fac:cliente_list')
#     permission_required = 'fac.add_cliente'
#     success_message = "Cliente creado satisfactoriamente"

#     def form_valid(self, form):
#         form.instance.uc = self.request.user #ubicamos al usuario que creo el formulario
#         return super().form_valid(form)

# class ClienteEdit(SuccessMessageMixin, Sin_Privilegios, generic.UpdateView):
#     model = Cliente
#     template_name = "fac/cliente_form.html"
#     context_object_name = "obj"
#     form_class = ClienteForm
#     success_url = reverse_lazy("fac:cliente_list") 
#     permission_required = 'fac.change_cliente'
#     success_message = "Cliente actualizado satisfactoriamente"

#     def form_valid(self, form):
#         form.instance.um = self.request.user.id #ubicamos al usuario que editó el formulario
#         return super().form_valid(form)

fac/templates/fac/cliente_form.html
<div class="modal-dialog modal-lg">  
    <div class="modal-content">
        
        {% if obj %}        
            <form method="POST" id="frmCliente" role="form" class="form-inline" action="{% url 'fac:cliente_edit' obj.pk %}">
        {% else %}
            <form method="POST" id="frmCliente" role="form" class="form-inline" action="{% url 'fac:cliente_new' %}">
        {% endif %}    

            {% csrf_token %}
            <div class="col-xl-12 col-md-12 mb-12">
    
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                    {% else %}
                    <div class="card border-left-succes shadow h-100 py-2">
                        {% endif %}
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                        {% if obj %} Editar {% else %} Nuevo {% endif %}Cliente
                                        
                                        {% if t %} En factura {% endif %}
                                    </div>
                                    <div class="dropdown-divider"></div>
                                    <div class="row">
                                        {{ form.as_p}}
                                    </div>
    
                                    <!-- {{ form.as_p }} -->
                                    <div class="dropdown-divider"></div>
                                    <div class="row">
                                        <div class="col">
                                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                                            <!-- <a href="{% url 'inv:um_list' %}" class="btn btn-success"><span class="fa fa-undo">Cancelar</span></a> -->
                                            <button type="button" class="btn btn-success" onclick="return cerrar_modal()">Cancelar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </form>
    </div>        
</div>


{% if t %}
    <script>
        $("#frmCliente").submit(function(e){
            var frm = $("#frmCliente");
            $.ajax({
                type: frm.attr('method'), // envio POST
                url: frm.attr('action'),
                data: frm.serialize(), // serializamos los datos del form
                success: function(data){
                    // alert(data);
                    window.location.reload(true);
                },
                error: function(data){
                    alert(data);
                }
            });

            return false;
        });
    </script>
{% endif %}
    

fac/templates/fac/cliente_list.html
{% extends 'base/base.html' %}

{% block page_content %}
 <!-- Dropdown Card Example -->
 <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                    <a class="dropdown-item" onclick="return abrir_modal('{% url 'fac:cliente_new' %}')"> <i class="far fa-calendar-plus"></i> Nuevo</a>
                    <!-- <a class="dropdown-item" href="#">Another action</a> -->
                <div class="dropdown-divider"></div>
                <!-- <a class="dropdown-item" href="#">Something else here</a> -->
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
       
       {% if not obj %}
            <div class="alert alert-info">No Hay Clientes</div>           
       {% endif %}
       <!-- <div class="buttons-toolbar">
            <button type="button" class="btn btn-primary" onclick="return abrir_modal('{% url 'fac:cliente_new' %}')"><i class="far fa-calendar-plus">Nuevo</i></button>
       </div> -->

       <table
            id="table"
            data-toggle="table"
            data-pagination="true"
            data-page-size="5"
            data-search="true"
            data-show-columns="true"
            data-show-fullscreen="true"
            data-show-toggle="true"
            data-show-export="true"
            data-click-to-select="true"
            data-locale="es-MX"
        >
           <thead>
               <th data-field="id" data-sortable="true">Id</th>
               <th data-field="nombres" data-sortable="true">Nombres</th>
               <th data-field="apellidos" data-sortable="true">Apellidos</th>
               <th>Celular</th>
               <th data-field="tipo" data-sortable="true">Tipo</th>
               <th>Estado</th>                                  
               <th class="all">Acciones</th>
           </thead>

           <tbody>               
               {% for item in obj %}
                   <tr>
                       <td>{{ item.id }}</td>
                       <td>{{ item.nombres }}</td>
                       <td>{{ item.apellidos }}</td>
                       <td>{{ item.celular }}</td>
                       <td>{{ item.tipo }}</td>                                          
                       <td>{# item.estado|yesno:"Activo,Inactivo" #}
                            <div onclick="inactivar({{ item.id }})">
                                <!-- si el cliente esta activo -->
                                {% if item.estado %} 
                                    <i class="far fa-thumbs-up text-primary"></i>
                                {% else %}
                                    <i class="far fa-thumbs-down text-danger"></i>
                                {% endif %}
                            </div>      
                       </td>
                       <td>
                            <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'fac:cliente_edit' item.id %}')"><i class="far fa-edit"></i></button>
                       </td>
                   </tr>
               {% endfor %}
                   
           </tbody>
       </table>       

    </div>
</div>

{% endblock page_content %}

{% block js_page %}

    <script>

        // Jquery para inactivar cliente
        function inactivar(id){
            var data = {id:id};
            data = JSON.stringify(data);
            var token = '{{csrf_token}}';
            // alert(token);
            // alert(id);            

            $.ajax({
                headers: {'X-CSRFToken': token},
                type: "POST",
                url: "estado/"+id,
                data: data,
                success: function(response){
                    if(response == "OK"){
                        location.reload(true);
                    }else{
                        mensaje("Error Intentando Cambiar Estado a Cliente");
                    }
                },
                error: function(jqXHR, textStatus, errorThrow){
                    console.log(textStatus, errorThrow);
                    mensaje(errorThrow, 'red');
                    cerrar_modal();
                }
            });

        }

        var $table = $('#table')

        $(function() {
            $('#toolbar').find('select').change(function () {
            $table.bootstrapTable('destroy').bootstrapTable({
                exportDataType: $(this).val(),
                exportTypes: ['json', 'xml', 'csv', 'txt', 'sql', 'excel', 'pdf'],
                columns: [
                {
                    field: 'state',
                    checkbox: true,
                    visible: $(this).val() === 'selected'
                },
                {
                    field: 'id',
                    title: 'ID'
                }, {
                    field: 'name',
                    title: 'Item Name'
                }, {
                    field: 'price',
                    title: 'Item Price'
                }
                ]
            })
            }).trigger('change')
        })

        // llamamos el dataTables jQuery plugin
        // $(function() {
        //     $("#sidebarToggle").click();
        //     $('.table').DataTable({
        //         "language": {
        //             "processing": "Procesando...",
        //             "lengthMenu": "Mostrar _MENU_ registros",
        //             "zeroRecords": "No se encontraron resultados",
        //             "emptyTable": "Ningún dato disponible en esta tabla",
        //             "infoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        //             "infoFiltered": "(filtrado de un total de _MAX_ registros)",
        //             "search": "Buscar:",
        //             "infoThousands": ",",
        //             "loadingRecords": "Cargando...",
        //             "paginate": {
        //                 "first": "Primero",
        //                 "last": "Último",
        //                 "next": "Siguiente",
        //                 "previous": "Anterior"
        //             },
        //             "aria": {
        //                 "sortAscending": ": Activar para ordenar la columna de manera ascendente",
        //                 "sortDescending": ": Activar para ordenar la columna de manera descendente"
        //             }
        //         }
        //     });
        // });
    </script>
    
{% endblock js_page%}
    

fac/templates/fac/factura_borrar_detalle.html
<label for="text-danger">¿Anular Producto <b>{{ det.producto.descripcion }}</b> de factura <b>{{ det.factura.id }}</b>?</label>
<div>
    <div class="form-group">
        <label for="control-label">Usuario</label>
        <input type="text" name="usuario" id="usuario" class="form-control" required>
    </div>

    <div class="form-group">
        <label for="control-label">Contraseña</label>
        <input type="password" name="password" id="password" class="form-control" required>
    </div>  
</div>

fac/templates/fac/factura_list.html
{% extends 'base/base.html' %}

{% block page_content %}
 <!-- Dropdown Card Example -->
 <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'fac:factura_new' %}"><i class="fa fa-calendar-plus"></i> Nuevo</a> 
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">

        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <label for="labelFecha1" class="form-label">Fecha #1</label>
                    <input type="text" class="form-class" name="f1" id="f1" readonly>
                </div>
                <div class="col-md-4">
                    <label for="labelFecha1" class="form-label">Fecha #2</label>
                    <input type="text" name="form-class" name="f2" id="f2" readonly>
                </div>
                <div class="col-md-4">
                    <button type="button" class="btn btn-warning" id="btnPrint">Imprimir</button>
                </div>
            </div>
        </div>
        <hr>
       
       {% if not obj %}
            <div class="alert alert-info">No Hay Clientes</div>           
       {% endif %}
       <!-- <div class="buttons-toolbar">
            <button type="button" class="btn btn-success"><i class="far fa-calendar-plus">Nuevo</i></button>
       </div> -->

       <table
            id="table"
            data-toggle="table"
            data-pagination="true"
            data-page-size="5"
            data-search="true"
            data-show-columns="true"
            data-show-fullscreen="true"
            data-show-toggle="true"
            data-locale="es-MX"
            data-toolbar = ".buttons-toolbar"
        >
           <thead>
               <th data-field="id" data-sortable="true">No. Factura</th>
               <th data-field="cliente" data-sortable="true">Cliente</th>
               <th data-field="total" data-sortable="true">Total</th>
               <th data-field="estado">Estado</th>                                  
               <th class="all">Acciones</th>
           </thead>

           <tbody>               
               {% for item in obj %}
                   <tr>
                       <td>{{ item.id }}</td>
                       <td>{{ item.cliente }}</td>
                       <td>{{ item.total }}</td>                                         
                       <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                       <td>
                            
                            <a href="{% url 'fac:factura_edit' item.id %}" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                       </td>
                   </tr>
               {% endfor %}
                   
           </tbody>
       </table>       

    </div>
</div>

{% endblock page_content %}

{% block js_page %}

    <script>
        // si ya cargo el DOM
        $(function(){
            // agregamos el calendario a los input
            $("#f1, #f2").datetimepicker({
                format: 'Y-m-d',
                timepicker: false
            });

            // evento del botón imprimir
            $("#btnPrint").click(function(e){
                e.preventDefault();

                var f1, f2;
                f1 = $("#f1").val(); // contenido del input 1
                f2 = $("#f2").val(); // contenido del input 2

                if(f1=="" || f1==null){ // esta vacio o nulo
                    f1 = "2019-06-01";
                }

                if(f2=="" || f2==null){
                    var d = new Date();
                    var f2 = d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate();
                }

                var url = "imprimir-todas/" + f1 + "/" + f2;
                //alert(url);

                window.open(url, 'facturas');
            });
        });
    </script>
    
{% endblock js_page%}
    