api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle

urlpatterns = [
    path('v1/productos/', ProductoList.as_view(), name='producto_list'),
    path('v1/productos/<str:codigo>/', ProductoDetalle.as_view(), name='producto_detalle'),
]

inv/urls.py
from django.urls import path

from inv.models import SubCategoria, UnidadMedida

from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, MarcaView, \
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
        MarcaView, MarcaNew, MarcaEdit, marca_inactivar, \
            UMView, UMNew, UMEdit, um_inactivar, \
                ProductoView, ProductoNew, ProductoEdit, producto_inactivar
            

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('marcas/', MarcaView.as_view(), name='marca_list'),
    path('marcas/new', MarcaNew.as_view(), name='marca_new'),
    path('marcas/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    path('marcas/inactivar/<int:id>', marca_inactivar, name='marca_inactivar'),

    path('um/', UMView.as_view(), name='um_list'),
    path('um/new', UMNew.as_view(), name='um_new'),
    path('um/edit/<int:pk>', UMEdit.as_view(), name='um_edit'),
    path('um/inactivar/<int:id>', um_inactivar, name='um_inactivar'),

    path('producto/', ProductoView.as_view(), name='producto_list'),
    path('producto/new', ProductoNew.as_view(), name='producto_new'),
    path('producto/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('producto/inactivar/<int:id>', producto_inactivar, name='producto_inactivar'),    
]

syscofa/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),    
]

bases/models.py
from django.db import models
from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey

# Create your models here.
class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True) #fecha de creación
    fm = models.DateTimeField(auto_now=True)     #fecha de modificación
    uc = models.ForeignKey(User, on_delete=models.CASCADE) #usuario de creación
    um = models.IntegerField(blank=True, null=True) #usuario de modificación

    class Meta:
        # se ignora este modelo al momento de hacer las migraciones
        abstract=True

class ClaseModelo2(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True) #fecha de creación
    fm = models.DateTimeField(auto_now=True)     #fecha de modificación
    # uc = models.ForeignKey(User, on_delete=models.CASCADE) #usuario de creación
    # um = models.IntegerField(blank=True, null=True) #usuario de modificación
    uc = UserForeignKey(auto_user_add=True, related_name='+')
    um = UserForeignKey(auto_user=True, related_name='+')

    class Meta:
        # se ignora este modelo al momento de hacer las migraciones
        abstract=True

inv/models.py
from re import T
from tabnanny import verbose
from django.db import models
from bases.models import ClaseModelo

# Create your models here.
class Categoria(ClaseModelo):
    """ modelo Categoría"""
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la categoría',
        unique=True
    )

    def __str__(self):
        """ Descripción del modelo categoria"""
        return '{}'.format(self.descripcion)

    def save(self):
        """ el valor de categoría lo guardamos en mayusculas"""
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        """ nombre en plural(Muchos) del modelo"""
        verbose_name_plural = "Categorias"

class SubCategoria(ClaseModelo):
    """ modelo SubCategoría"""
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text="Descripción de la categoria",        
    )

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        """ el valor de subcategoría lo guardamos en mayúsculas"""
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        """ nombre en plural(Muchos) del modelo"""
        verbose_name_plural = "Sub Categorias"
        unique_together = ('categoria','descripcion')

class Marca(ClaseModelo):
    """ modelo Marca"""
    descripcion = models.CharField(
        max_length=100,
        help_text="Descripción de la marca",
        unique=True
    )

    def __str__(self):
        """ descripción del modelo marca"""
        return '{}'.format(self.descripcion)

    def save(self):
        """ el valor de marca lo guardamos en mayusculas"""
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

    class Meta:
        """ nombre en plural(Muchos) del modelo"""
        verbose_name_plural = "Marcas"

class UnidadMedida(ClaseModelo):
    """ modelo Unidad de Medida"""
    descripcion = models.CharField(
        max_length=100,
        help_text="Descripción de la Unidad de Medida",
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        """ el valor de Unidad de Medida lo guardamos en mayúsculas"""
        self.descripcion = self.descripcion.upper()
        super(UnidadMedida, self).save()
    class Meta:
        """ nombre en plural(Muchos) del modelo"""
        verbose_name_plural = "Unidades de Medida"

class Producto(ClaseModelo):
    """ modelo Producto"""
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True) 

    # llaves foraneas
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self):
        """ descripción de producto"""
        return '{}'.format(self.descripcion)

    def save(self):
        """ el valor de Producto lo guardamos en mayúsculas"""
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()
    class Meta:        
        """ nombre en plural(Muchos) del modelo"""
        verbose_name_plural = "Productos"
        unique_together = ('codigo', 'codigo_barra')

inv/views.py
from pyexpat import model
from re import template
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required

from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto
from .forms import CategoriaForm, SubCategoriaForm, MarcaForm, UMForm, ProductoForm
from bases.views import Sin_Privilegios

# Create your views here.
class CategoriaView(Sin_Privilegios, generic.ListView):
    """ vista basada en clase que lista las categorías"""
    permission_required = 'inv.view_categoria'
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"

class CategoriaNew(SuccessMessageMixin, Sin_Privilegios, generic.CreateView):
    """ vista basada en clase para crear una nueva categoría"""
    permission_required = 'inv.add_categoria'
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class =  CategoriaForm #formulario a utilizar
    success_message = "Categoría creada satisfactoriamente"
    success_url = reverse_lazy("inv:categoria_list") #redireccionamos a la lista de categorías
   
    def form_valid(self, form):
        form.instance.uc = self.request.user #ubicamos al usuario que creo el formulario
        return super().form_valid(form)

class CategoriaEdit(SuccessMessageMixin, Sin_Privilegios, generic.UpdateView):    
    """ vista basada en clase para editar y/o actualizar una categoría"""
    permission_required = 'inv.change_categoria'
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class =  CategoriaForm #formulario a utilizar
    success_message = "Categoría actualizada satisfactoriamente"
    success_url = reverse_lazy("inv:categoria_list") #redireccionamos a la lista de categorías
    
    def form_valid(self, form):
        form.instance.um = self.request.user.id #ubicamos al usuario que modificó el formulario
        return super().form_valid(form)

class CategoriaDel(SuccessMessageMixin, Sin_Privilegios, generic.edit.DeleteView):
    """ vista basada en clase para eliminar una categoría"""
    permission_required = 'inv.delete_categoria'
    model = Categoria
    template_name = "inv/categoria_del.html"
    context_object_name = "obj"
    success_message = "Categoría eliminada satisfactoriamente"
    success_url = reverse_lazy("inv:categoria_list")
    
class SubCategoriaView(Sin_Privilegios, generic.ListView):
    """ vista basada en clase que lista las subcategorías"""
    permission_required = "inv.view_subcategoria"
    model = SubCategoria
    template_name = "inv/subcategoria_list.html"
    context_object_name = "obj"

class SubCategoriaNew(SuccessMessageMixin, Sin_Privilegios, generic.CreateView):
    """ vista basada en clase para crear una nueva subcategoría"""
    permission_required = "inv.add_subcategoria"
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class =  SubCategoriaForm #formulario a utilizar
    success_message = "Sub Categoría creada correctamente"
    success_url = reverse_lazy("inv:subcategoria_list") #redireccionamos a la lista de subcategorías

    def form_valid(self, form):
        form.instance.uc = self.request.user #ubicamos al usuario que creo el formulario
        return super().form_valid(form)

class SubCategoriaEdit(SuccessMessageMixin, Sin_Privilegios, generic.UpdateView):    
    """ vista basada en clase para editar y/o actualizar una subcategoría"""
    permission_required = "inv.change_subcategoria"
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class =  SubCategoriaForm #formulario a utilizar
    success_message = "Sub Categoría actualizada correctamente"
    success_url = reverse_lazy("inv:subcategoria_list") #redireccionamos a la lista de subcategorías
    
    def form_valid(self, form):
        form.instance.um = self.request.user.id #ubicamos al usuario que modificó el formulario
        return super().form_valid(form)

class SubCategoriaDel(SuccessMessageMixin, Sin_Privilegios, generic.edit.DeleteView):
    """ vista basada en clase para eliminar una subcategoría"""
    model = SubCategoria
    template_name = "inv/catalogos_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy("inv:subcategoria_list")
    success_message = "Sub Categoría eliminada correctamente"
    permission_required = "inv.delete_subcategoria"

class MarcaView(Sin_Privilegios, generic.ListView):
    """ vista basada en clase que lista las marcas"""
    permission_required = 'inv.view_marca'
    model = Marca
    template_name = "inv/marca_list.html"
    context_object_name = "obj"

class MarcaNew(SuccessMessageMixin, Sin_Privilegios, generic.CreateView):
    """ vista basada en clase para crear una nueva marca"""
    model = Marca
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class =  MarcaForm #formulario a utilizar
    success_url = reverse_lazy("inv:marca_list") #redireccionamos a la lista de marcas
    success_message = "Marca creada correctamente"
    permission_required = "inv.add_marca"

    def form_valid(self, form):
        form.instance.uc = self.request.user #ubicamos al usuario que creo el formulario
        return super().form_valid(form)

class MarcaEdit(SuccessMessageMixin, Sin_Privilegios, generic.UpdateView):    
    """ vista basada en clase para editar y/o actualizar una marca"""
    model = Marca
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class =  MarcaForm #formulario a utilizar
    success_url = reverse_lazy("inv:marca_list") #redireccionamos a la lista de marcas
    success_message = "Marca actualizada correctamente"
    permission_required = "inv.change_marca"

    def form_valid(self, form):
        form.instance.um = self.request.user.id #ubicamos al usuario que modificó el formulario
        return super().form_valid(form)

@login_required(login_url='/login/') #debo estar logeado
@permission_required('inv.change_marca', login_url='bases:sin_privilegios') #y tener permiso para modificar
def marca_inactivar(request, id):
    """ vista que inactiva una marca"""
    marca = Marca.objects.filter(pk=id).first()
    contexto = {}
    template_name="inv/marca_inactivar.html"

    if not marca:
        return redirect("inv:marca_list")

    if request.method == 'GET':
        contexto = {'obj': marca}

    if request.method == 'POST':
        marca.estado = False
        marca.save()
        messages.success (request, 'Marca Inactivada')
        return redirect('inv:marca_list')

    return render(request, template_name, contexto)

class UMView(Sin_Privilegios, generic.ListView):
    """ vista basada en clase que lista las unidades de medida"""
    model = UnidadMedida
    template_name = "inv/um_list.html"
    context_object_name = "obj"
    permission_required = "inv.view_unidadmedida"

class UMNew(SuccessMessageMixin, Sin_Privilegios, generic.CreateView):
    """ vista basada en clase para crear una nueva unidad de medida"""
    model = UnidadMedida
    template_name = "inv/um_form.html"
    context_object_name = "obj"
    form_class =  UMForm #formulario a utilizar
    success_url = reverse_lazy("inv:um_list") #redireccionamos a la lista de unidades de medida
    success_message = "Unidad de Medida creada correctamente"
    permission_required = "inv.add_unidadmedida"

    def form_valid(self, form):
        form.instance.uc = self.request.user #ubicamos al usuario que creo el formulario
        return super().form_valid(form)

class UMEdit(SuccessMessageMixin, Sin_Privilegios, generic.UpdateView):    
    """ vista basada en clase para editar y/o actualizar una unidad de medida"""
    model = UnidadMedida
    template_name = "inv/um_form.html"
    context_object_name = "obj"
    form_class =  UMForm #formulario a utilizar
    success_url = reverse_lazy("inv:um_list") #redireccionamos a la lista de unidades de medida
    success_message = "Unidad de Medida actualizada correctamente"
    permission_required = "inv.change_unidadmedida"

    def form_valid(self, form):
        form.instance.um = self.request.user.id #ubicamos al usuario que modificó el formulario
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_unidadmedida', login_url='bases:sin_privilegios')
def um_inactivar(request, id):
    """ vista que inactiva una unidad de medida"""
    um = UnidadMedida.objects.filter(pk=id).first()
    contexto = {}
    template_name="inv/um_inactivar.html"

    if not um:
        return redirect("inv:um_list")

    if request.method == 'GET':
        contexto = {'obj': um}

    if request.method == 'POST':
        um.estado = False
        um.save()
        return redirect('inv:um_list')

    return render(request, template_name, contexto)

class ProductoView(Sin_Privilegios, generic.ListView):
    """ vista basada en clase que lista los productos"""
    model = Producto
    template_name = "inv/producto_list.html"
    context_object_name = "obj"
    permission_required = "inv.view_producto"

class ProductoNew(SuccessMessageMixin, Sin_Privilegios, generic.CreateView):
    """ vista basada en clase para crear una nuevo producto"""
    model = Producto
    template_name = "inv/producto_form.html"
    context_object_name = "obj"
    form_class =  ProductoForm #formulario a utilizar
    success_url = reverse_lazy("inv:producto_list") #redireccionamos a la lista de productos
    success_message = "Producto creado correctamente"
    permission_required = "inv.add_producto"

    def form_valid(self, form):

inv/templates/inv/categoria_form.html
{% extends 'base/base.html' %}

{% block page_content %}
   <form method="POST" class="form-inline">
       {% csrf_token %}
        <div class="col-xl-6 col-md-6 mb-6">
            
            {% if obj %}      
                <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
                <div class="card border-left-succes shadow h-100 py-2">
            {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nueva {% endif %} Categoría 
                            </div>                        
                            <div class="dropdown-divider"> </div>
                            <div class="row">                               
                                <div class="col-10">
                                    <div class="input-group">
                                        <!-- <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción:"
                                        value="{% if obj %} {{ obj.descripcion }} {% endif %}"> -->
                                        {{ form.descripcion }}
                                    </div>                                    
                                </div>
                                <div class="col-2">
                                    <div class="input-group">
                                        <label for="id_estado">Estado</label>
                                        <!-- <input type="checkbox" name="estado" class="form-control" id="id_estado" value="{% if obj.estado %} checked {% endif %}"> -->
                                        {{ form.estado }}
                                    </div>
                                </div>
                                
                            </div>

                             <!-- {{ form.as_p }} -->
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                 <div class="col">
                                    <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                                    <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo">Cancelar</span></a>
                                </div>
                            </div>                                
                            
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
   </form>  
{% endblock page_content %}    
{% block js_page %} {% endblock js_page %}
    

inv/templates/inv/producto_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">

        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inv:producto_edit' obj.pk %}">
            {% else %}
            <form method="POST" role="form" class="form-inline" action="{% url 'inv:producto_new' %}">
                {% endif %}

                {% csrf_token %}
                <div class="col-xl-12 col-md-12 mb-12">

                    {% if obj %}
                    <div class="card border-left-warning shadow h-100 py-2">
                        {% else %}
                        <div class="card border-left-succes shadow h-100 py-2">
                            {% endif %}
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                            {% if obj %} Editar {% else %} Nuevo {% endif %}Producto
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        <div class="row">
                                            {#{ form.as_p}#}
                                        </div>

                                        <!-- fila 1 -->
                                        <div class="row my-1">
                                            <div class="col-md-6">
                                                <div class="col-md-6">{{ form.codigo.label }}</div>
                                                <div class="col-md-6">{{ form.codigo }}</div>
                                            </div>

                                            <div class="col-md-6">
                                                <div class="col-md-6">{{ form.codigo_barra.label }}</div>
                                                <div class="col-md-6">{{ form.codigo_barra }}</div>
                                            </div>
                                        </div>

                                        <!-- fila 2 -->
                                        <div class="row my-1">
                                            <div class="col-md-6">
                                                <div class="col-md-6">{{ form.descripcion.label }}</div>
                                                <div class="col-md-6">{{ form.descripcion }}</div>
                                            </div>

                                            <div class="col-md-6 my-1">
                                                <div class="col-md-6">{{ form.estado.label }}</div>
                                                <div class="col-md-6">{{ form.estado }}</div>

                                                <!-- <div class="col-md-12 py-4 pl-md-5">
                                                    <div class="form-check">
                                                        <input class="form-check-input" type="checkbox" value=""
                                                            id="flexCheckDefault">
                                                        <label class="form-check-label" for="flexCheckDefault">
                                                            {{ form.estado.label }}
                                                        </label>
                                                    </div>
                                                </div> -->
                                            </div>
                                        </div>

                                        <!-- fila 3 -->
                                        <div class="row my-1">
                                            <div class="col-md-6">
                                                <div class="col-md-6">{{ form.precio.label }}</div>
                                                <div class="col-md-6">{{ form.precio }}</div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="col-md-6">{{ form.existencia.label }}</div>
                                                <div class="col-md-6">{{ form.existencia }}</div>
                                            </div>
                                        </div>

                                        <!-- fila 4 -->
                                        <div class="row">
                                            <div class="col-md-4 my-1">
                                                <div class="col-md-12">{{ form.ultima_compra.label }}</div>
                                                <div class="col-md-6">{{ form.ultima_compra }}</div>
                                            </div>

                                            <div class="col-md-4 my-1">
                                                <div class="col-md-12">{{ form.marca.label }}</div>
                                                <div class="col-md-6">{{ form.marca }}</div>
                                            </div>
                                            <div class="col-md-4 my-1">
                                                <div class="col-md-12">{{ form.unidad_medida.label }}</div>
                                                <div class="col-md-4">{{ form.unidad_medida }}</div>
                                            </div>
                                        </div>

                                        <!-- fila 5 -->
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="col-md-12 my-1">Categoría</div>
                                                <div class="col-md-6">
                                                    <select name="categoria" id="id_categoria"
                                                        class="form-control form-control-md">
                                                        <option value="0">-------</option>

                                                        {% for item in categorias %}
                                                        <option value="{{ item.id }}">{{ item.descripcion }}</option>
                                                        {% endfor %}

                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-6">
                                                <div class="col-md-12 my-1">Sub Categoría</div>
                                                <div class="col-md-6">
                                                    <select name="subcategoria" id="id_subcategoria"
                                                        class="form-control form-control-md">
                                                        <option value="0">-------</option>

                                                        {% for item in subcategorias %}
                                                            <option value="{{ item.id }}" data-chained="{{ item.categoria.id }}">
                                                                {{ item.descripcion }}
                                                            </option>
                                                        {% endfor %}

                                                    </select>
                                                </div>
                                            </div>
                                           

                                            <!-- <select id="mark" name="mark">
                                                <option value="">--</option>
                                                <option value="bmw">BMW</option>
                                                <option value="audi">Audi</option>
                                            </select>
                                            <select id="series" name="series">
                                                <option value="">--</option>
                                                <option value="series-3" data-chained="bmw">3 series</option>
                                                <option value="series-5" data-chained="bmw">5 series</option>
                                                <option value="series-6" data-chained="bmw">6 series</option>
                                                <option value="a3" data-chained="audi">A3</option>
                                                <option value="a4" data-chained="audi">A4</option>
                                                <option value="a5" data-chained="audi">A5</option>
                                            </select> -->

                                        </div> 

                                        <!-- {{ form.as_p }} -->
                                        <div class="dropdown-divider"></div>
                                        <div class="row">
                                            <div class="col">
                                                <button type="submit" class="btn btn-danger"><span
                                                        class="fa fa-save"></span>Guardar</button>
                                                <!-- <a href="{% url 'inv:um_list' %}" class="btn btn-success"><span class="fa fa-undo">Cancelar</span></a> -->
                                                <button type="button" class="btn btn-success"
                                                    onclick="return cerrar_modal()">Cancelar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    // carga del DOM
    $(function(){
        $("#id_categoria").val("{{ obj.subcategoria.categoria.id }}") // pinta la categoria
        $("#id_subcategoria").val("{{ obj.subcategoria.id }}").change(); // pinta la subcategoria        
        $("#id_subcategoria").chained("#id_categoria"); // vinculamos los 2 select
    });
</script>